# Generated by Django 4.0.3 on 2022-03-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theinsta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='MyBlog!', max_length=255),
        ),
    ]
